import { makeStyles } from "@material-ui/core/styles";

const musicPageStyles = makeStyles({
  page: {},
});

const playListStyles = makeStyles({
  page: {
    position: "absolute",
    width: "100%",
    height: "100%",
    top: 0,
    left: 0,
  },
  background: {
    position: "absolute",
    width: "100%",
    height: "100%",
    top: 0,
    left: 0,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  container: {
    position: "absolute",
    width: "94%",
    height: "60%",
    bottom: 0,
    margin: "1px 3% 8px 3%",
    borderRadius: "20px",
    backgroundColor: "white",
  },
  close_button: {
    position: "absolute",
    width: "40px",
    height: "40px",
    top: 0,
    left: 0,
    zIndex: 100,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    position: "absolute",
    width: "100%",
    height: "40px",
    display: "flex",
    fontSize: "20px",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  content: {
    position: "absolute",
    width: "100%",
    height: "100%",
    paddingTop: "40px",
    paddingBottom: "40px",
    boxSizing: "border-box",
  },
  music_list: {
    width: "100%",
    height: "100%",
    paddingTop: "15px",
    boxSizing: "border-box",
    overflowY: "scroll",
  },
  music_item: {
    width: "100%",
    height: "35px",
    marginBottom: "12px",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  music_name: {
    width: "calc(100% - 130px)",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  music_name_big: {
    fontSize: "14px",
  },
  music_name_small: {
    fontSize: "10px",
  },
  buttons: {
    width: "130px",
    height: "100%",
    paddingRight: "10px",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  button: {
    margin: "0px 3px",
  },
  music_loading: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  add_button_content: {
    position: "absolute",
    width: "100%",
    height: "40px",
    bottom: 0,
    left: 0,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  add_button: {
    
  },
});

const musicOnShowStyles = makeStyles({
  page: {
    position: "absolute",
    zIndex: 1000,
    width: "100%",
    height: "100%",
    top: 0,
    left: 0,
    backgroundColor: "white",
  },
  container: {
    position: "absolute",
    width: "100%",
    height: "100%",
    top: 0,
    left: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  hide_button: {
    position: "absolute",
    width: "40px",
    height: "40px",
    top: "5px",
    left: "5px",
    zIndex: 1000,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  music_container: {
    position: "absolute",
    width: "100%",
    height: "100%",
    top: 0,
    left: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
  },
  background_img: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    filter: "blur(5px)",
    opacity: 0.65,
  },
  music_img_content: {
    width: "100%",
    height: "75%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  img_content: props => ({
    width: props.clientWidth * 0.8,
    height: props.clientWidth * 0.8,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: props.clientWidth * 0.4,
    overflow: "hidden",
  }),
  img: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  music_content: {
    width: "100%",
    height: "25%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  music_name: {
    width: "50%",
    textAlign: "center",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  slider: {
    width: "80%",
    boxSizing: "border-box",
  },
  buttons: {
    width: "100%",
    marginTop: "3%",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  a_button: {
    margin: "0 4%",
  },
  box: {
    position: "absolute",
    width: "100%",
    height: "100%",
    top: 0,
    left: 0,
    zIndex: 1500,
    overflow: "hidden",
  },
});

const musicHideStyles = makeStyles({
  page:{
    position: "absolute",
    zIndex: 1000,
    width: 50,
    height: 50,
    bottom: 60,
    right: 25,
    borderRadius: 25,
    overflow: "hidden",
  },
  container: {
    position: "absolute",
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  background: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  canvas: {
    position: "absolute",
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.15)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  }
});

export { 
  musicPageStyles, 
  musicOnShowStyles, 
  musicHideStyles,
  playListStyles
};